AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Style/AsciiComments:
  Enabled: false

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
      inject: 'inject'

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - spec/**/*_spec.rb

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/SignalException:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/FormatString:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/WordArray:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - examples/*.rb
    - Gemfile
    - lib/faraday-http-cache.rb
    - Rakefile

Style/TrivialAccessors:
  AllowPredicates: true

Style/NumericPredicate:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/faraday-http-cache.rb
